[package]
description = "IDE-style terminal emulator built on woocraft and GPUI."
name        = "recoil-term"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
publish      = false
readme       = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }

[lints]
workspace = true

[features]
default   = ["resources"]
resources = ["woocraft/resources"]
tray      = ["woocraft/tray"]

[dependencies]
recoil-core       = { workspace = true }
woocraft          = { workspace = true }
woocraft-terminal = { workspace = true }

anyhow     = { workspace = true }
chrono     = { workspace = true }
rust-i18n  = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
ulid       = { workspace = true }
